package-lock.json, package.json
=> feat(): v1.0.0 release kucoin-api node.js SDK for REST API and WebSockets

docs/endpointFunctionList.md, package-lock.json, package.json, src/FuturesClient.ts, src/SpotClient.ts, src/types/response/spot-trading.ts
v1.0.5 feat(): 
added new endpoints
updated types
updated endpoint map table
=> v1.0.5 feat(): added new endpoints, updated types, updated endpoint map table

.github/workflows/templates-readme.yml, README.md, package-lock.json, package.json, src/FuturesClient.ts
=> feat(): updated Readme actions

package-lock.json, package.json, src/FuturesClient.ts, src/SpotClient.ts, src/types/request/futures.types.ts, src/types/request/spot-funding.ts, src/types/response/futures.types.ts, src/types/response/spot-funding.ts, src/types/response/spot-trading.ts
=> feat(): added new endpoints, deprecated old endpoints, updated types

package-lock.json, package.json, src/FuturesClient.ts
=> fix(): fixed small url typo

package-lock.json, package.json, src/SpotClient.ts
=> fix(): updated params to match the docs

docs/endpointFunctionList.md, examples/apidoc/FuturesClient/cancelAllOrdersV3.js, package-lock.json, package.json, src/FuturesClient.ts, src/SpotClient.ts
v1.0.21 feat(): deprecated function, added replacment
=> v1.0.21 feat(): deprecated cancelAllOrders, added cancelAllOrdersV3, fixed missing auth for getMarginLeveragedToken & getMarginRiskLimitConfig

package-lock.json, package.json, src/types/response/spot-funding.ts
fixes #45 
v1.0.22 - updated GetMarginBalance response type
=> fix(#45): v1.0.22 - updated GetMarginBalance response type

docs/endpointFunctionList.md, examples/apidoc/SpotClient/getMarginLeveragedToken.js, examples/apidoc/SpotClient/getMarginRiskLimitConfig.js, package-lock.json, package.json, src/FuturesClient.ts, src/SpotClient.ts
Kucoin created new V2 docs and marked a lot of endpoints as abandoned. 
Check this link for more info:
https://www.kucoin.com/docs-new/abandoned-endpoints/introduction
=> chore(): v1.0.23 - marked all abandoned endpoints for deprecation

package-lock.json, package.json, test/REST/private.test.ts, test/proxy.util.ts
=> chore(v2.0.3): bump dependencies, more test logs

package-lock.json, package.json, src/BrokerClient.ts, src/index.ts, src/lib/requestUtils.ts, src/types/request/broker.types.ts, src/types/response/broker.types.ts
feat(v2.1.0): Full support for Exchange Broker endpoints
- added new BrokerClient for exchange broker endpoints
- full type support for requests and responses
=> feat(v2.1.0): Full support for Exchange Broker endpoints

package-lock.json, package.json, src/SpotClient.ts, src/types/request/spot-account.ts, src/types/request/spot-funding.ts
feat(v2.1.1): 
added "getMyIP" endpoint
added new req params for getAccountHFTransactions and getTransferableRequest
=> feat(v2.1.1): added "getMyIP" endpoint, added new req params

docs/endpointFunctionList.md, examples/apidoc/SpotClient/getDiscountRateConfigs.js, examples/apidoc/SpotClient/getMyIp.js, package-lock.json, package.json, src/SpotClient.ts, src/types/response/spot-vip.ts
feat(v2.1.2): added getDiscountRateConfigs() endpoint
=> feat(v2.1.2): added getDiscountRateConfigs() endpoint

package-lock.json, package.json, src/lib/BaseWSClient.ts, src/lib/websocket/websocket-util.ts
- added safeTerminateWs() function
=> feat(v2.1.3): added safeTerminateWs()

docs/endpointFunctionList.md, package-lock.json, package.json, src/SpotClient.ts, src/types/response/futures.types.ts
feat(v2.1.5): added response params for AccountBalance, added req type for getSubaccountBalance()
=> feat(v2.1.5): added response params for AccountBalance, added req type for getSubaccountBalance()

docs/endpointFunctionList.md, examples/apidoc/FuturesClient/batchSwitchMarginMode.js, examples/apidoc/FuturesClient/getCrossMarginRiskLimit.js, package-lock.json, package.json, src/FuturesClient.ts, src/types/response/futures.types.ts, src/types/response/spot-funding.ts
feat(v2.1.8): added new endpoints for batch margin update and cross margin risk limit, added liability type parameters
=> feat(v2.1.8): added new endpoints for batch margin update and cross margin risk limit, added liability type parameters

package-lock.json, package.json, src/types/response/futures.types.ts
chore(2.1.9): add funding updated response params
=> chore(2.1.9): add funding updated response params

package-lock.json, package.json, src/SpotClient.ts, src/index.ts
As part of the PR, make sure you have:
=> chore(): fix linter

docs/endpointFunctionList.md, examples/apidoc/FuturesClient/getCrossMarginRequirement.js, llms.txt, package-lock.json, package.json, src/FuturesClient.ts, src/types/response/futures.types.ts
As part of the PR, make sure you have:
=> feat(2.1.19): added cross margin new endpoint

docs/endpointFunctionList.md, examples/apidoc/WebsocketAPIClient/cancelFuturesOrder.js, examples/apidoc/WebsocketAPIClient/cancelMarginOrder.js, examples/apidoc/WebsocketAPIClient/cancelMultipleFuturesOrders.js, examples/apidoc/WebsocketAPIClient/cancelSpotOrder.js, examples/apidoc/WebsocketAPIClient/cancelSyncSpotOrder.js, examples/apidoc/WebsocketAPIClient/modifySpotOrder.js, examples/apidoc/WebsocketAPIClient/submitFuturesOrder.js, examples/apidoc/WebsocketAPIClient/submitMarginOrder.js, examples/apidoc/WebsocketAPIClient/submitMultipleFuturesOrders.js, examples/apidoc/WebsocketAPIClient/submitNewSpotOrder.js, examples/apidoc/WebsocketAPIClient/submitSyncSpotOrder.js, llms.txt
As part of the PR, make sure you have:
=> feat(): Added examples
